### ISSUE TITLE
Hydrogenation is failing to observe coplanar rules.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/primarydock#287] opened 2023-06-28 14:54 UTC
This is from the hGNAL PDB:

![image](https://github.com/primaryodors/primarydock/assets/66374250/e2a5ca88-c84a-4628-b175-88f486086ee9)

**Comment by primaryodors** [comment] 2023-06-28 17:20
This should be fixed right away before continuing with the cron fixes.

Would also be good to create a unit test for coplanar hydrogens in side chains that should have them: Arg, Asn, Gln, His, Phe, Trp, Tyr.

**Comment by ssepeq** [comment] 2023-07-12 04:08
The coupled homology branch has a fix for this one.

**Comment by primaryodors** [comment] 2023-07-14 03:37
It looks like the way to test this would be to re-add the `hydrogenate_add_missing_heavy_atoms` code, enable it, and generate a coupled PDB.

**Comment by primaryodors** [comment] 2023-07-14 04:23
Confirmed, still happening, in both the G protein (first image) and the receptor (second image).

![image](https://github.com/primaryodors/primarydock/assets/106125032/cec3083d-6334-4eda-bb25-12f29ed3424d)
![image](https://github.com/primaryodors/primarydock/assets/106125032/6055f45a-dc13-4a39-abe4-86e030afaf62)

**Comment by primaryodors** [comment] 2023-07-14 05:09
There are missing and extra hydrogens, but coplanarity is being observed now.

![image](https://github.com/primaryodors/primarydock/assets/106125032/ef95b560-b359-4198-9c32-f53a06f4e51e)
![image](https://github.com/primaryodors/primarydock/assets/106125032/6c4848e0-d3dd-467e-991d-576304c17609)

**Closed** 2023-07-14 14:39 UTC
Labels: CRITICAL, retest
